name: Create and publish a Docker image

on:
  push:
  schedule:
    - cron: "17 17 * * *" # Run at 17:17 every day

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  IMAGE_TAG: kizzycode/ws2812b-cgi:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Setup environment
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # Build images
      # NOTE: if you change the platforms here, you must also adjust the push section
      - name: Build for linux/arm/v7
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: linux/arm/v7
      
      - name: Build for linux/arm64
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: linux/arm64

      - name: Build for linux/amd64
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: linux/amd64
      
      
      # Push images
      # NOTE: if you change the platforms here, you must also adjust the build section
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Push to registry for linux/amd64,linux/arm64,linux/arm/v7,linux/386
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}"
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
